### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by NoSloppy**
A collection of images I've whipped up over the years to explain things to people.
Maybe they can live in the images folder for now, until linked to from related pages?
Preview:
a_humstart_vs_ProffieOSHumDelay
AccentSwingThresholds
Blade_Detect_basic_config_format
Blade_Integer_Reference
BladeIntegerPercentageValuesFunctions
board_orientations
Font_Folder_Optimized
Mono-vs-poly_font
Preset_syntax
Tilt
twist
Varitaion-Colors
Volume_Percentages

### CODE REVIEW

**Comment by profezzorn** [comment]
Most of these images are pretty reasonable, but it would be nice if they were higher resolution.
Some of them should be replaced with actual text though, especially the config file one.

**Comment by profezzorn** [comment]
Also, the orientation image uses defines that don't exist in the code yet, that will be confusing if people try to use those defines.

**Comment by NoSloppy** [comment]
> Also, the orientation image uses defines that don't exist in the code yet, that will be confusing if people try to use those defines.

Updated to include "previously known as"

**Comment by NoSloppy** [comment]
> Some of them should be replaced with actual text though, especially the config file one.

Blade Detect and Blade ID updated with config file templates in text, not images.

**Pull request merged**
